# Herobrine’s battle

Alex jumped to Endy, but Endy knocked Alex back. “Ah!” Alex said as she fell down next to Felix and Malek. Now, Bob and I were the only ones not hurt. 

Then all of the bad guys combined their strength to make a giant laser to destroy us. The bad guys shot Bob and me with the laser so we could not battle. 

Next Herobrine tried to take over the world. But when he tried, it didn’t work. 

Herobrine said, “Noooooooo, there’s a lifelock.”

I said, “Ha!”

Herobrine said, “I know the lifelock is in Beckett’s brain,”

Herobrine went into my brain to find memory 57 where the lifelock was stored.

Then Bob said, “The only way to kill Herobrine now is to kill Beckett.”

So Bob killed me so he could kill Herobrine.

As he died, Herobrine said, “Noooooooooo!”

The bad guys were really sad and said, “We lost our leader. We should go home and have a funeral.”

And so the world was saved and everyone recovered, but I was still dead. 

Then all of the crystals said, “Thank you for saving us. As your reward, we will now save Beckett.”

Then I came back to life too, and I said, “Thank you for saving me!”
